name:                tintin
version:             1.2.4
github:              "theam/tintin"
license:             Apache-2.0
author:              "The Agile Monkeys"
maintainer:          "hackers@theam.io"
copyright:           "2018 Theam"
license-file:        LICENSE.md

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            A softer alternative to Haddock
category:            Documentation

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the website <https://theam.github.io/tintin>

default-extensions:
- DeriveGeneric
- RecordWildCards
- OverloadedStrings
- DataKinds
- TypeOperators
- NoImplicitPrelude
- StandaloneDeriving
- TypeApplications
- KindSignatures
- FlexibleContexts
- FlexibleInstances
- MultiParamTypeClasses
- TypeFamilies

dependencies:
  - base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - text
  - directory
  - temporary
  - process
  - inliterate
  - universum
  - lucid
  - yaml
  - clay
  - data-has
  - frontmatter



executables:
  tintin:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tintin
    - universum
    - optparse-generic

tests:
  tintin-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tintin
